"""
services/llm_prioritizer.py — LLM-assisted contextual synthesis engine.

Supports Groq (free fast inference for demos), Gemini, OpenAI, and Mock providers.
Applies strict pre-call secret redaction and graceful offline fallbacks.
"""

import json
import logging
import urllib.request
import urllib.error
from typing import Any, Optional
from pydantic import BaseModel, Field

from src.app.config import settings
from src.app.schemas.canonical import NormalizedFinding
from src.app.schemas.dedup import CanonicalIssue
from src.app.schemas.risk import LLMContext, ThreatEnrichment
from src.app.schemas.validation import ValidationResult, ValidationStatus
from src.app.services.extractor import redact_secrets

logger = logging.getLogger(__name__)


class LLMContextualAnalysis(BaseModel):
    """Structured contextual prioritization analysis generated by or modeled after an LLM."""
    contextual_summary: str
    exploitability_assessment: str
    sandbox_evidence_synthesis: str
    recommended_action: str
    confidence: float = Field(ge=0.0, le=1.0)
    model_used: str


class LLMPrioritizerService:
    def analyze(
        self,
        issue: CanonicalIssue,
        finding: NormalizedFinding,
        validation: Optional[ValidationResult],
        threat_enrichments: list[ThreatEnrichment],
    ) -> Optional[LLMContextualAnalysis]:
        """
        Synthesize finding context, sandbox empirical evidence, and threat intel.
        Returns structured analysis or None if disabled.
        """
        if not settings.llm_enabled and settings.llm_provider != "mock":
            return None

        # Build redacted context
        param = redact_secrets(finding.location.parameter or "input")
        path = redact_secrets(finding.location.path or finding.location.url or "/endpoint")
        title = redact_secrets(finding.vulnerability.title)
        cwe = finding.vulnerability.cwe_primary or "Unknown CWE"
        has_kev = any(t.kev_flag for t in threat_enrichments)
        max_epss = max((t.epss_score for t in threat_enrichments), default=0.0)

        # Grounding in empirical sandbox validation evidence
        if validation and validation.status == ValidationStatus.SIMULATED_MATCH:
            exploitability = "High (Reproducible in Lab)"
            sandbox_note = (
                f"Empirical sandbox probe against parameter '{param}' at '{path}' "
                f"triggered expected {validation.scenario.upper()} behavior with "
                f"{int((validation.confidence or 0.75) * 100)}% confidence."
            )
            summary = (
                f"High-priority actionable vulnerability: {title} ({cwe}) was verified "
                f"in the safe lab sandbox on parameter '{param}'. The endpoint responded with matching "
                f"vulnerability markers. Given {'active CISA KEV exploitation and ' if has_kev else ''}"
                f"EPSS score of {max_epss:.2f}, immediate remediation is recommended."
            )
            action = f"Apply input validation and contextual encoding/parameterization for parameter '{param}'."
            conf = validation.confidence or 0.85
        elif validation and validation.status == ValidationStatus.SIMULATED_NO_MATCH:
            exploitability = "Low / Mitigated (Unreproducible under test)"
            sandbox_note = (
                f"Controlled sandbox probe against parameter '{param}' did not trigger "
                f"vulnerable execution; server returned sanitized or rejecting response."
            )
            summary = (
                f"Likely mitigated or lower-severity finding: Lab simulation for {title} on '{param}' "
                f"failed to reproduce the reported behavior. Priority may be safely downgraded."
            )
            action = "Verify defensive controls in staging before closing as mitigated/false positive."
            conf = 0.70
        elif validation and validation.status == ValidationStatus.INCONCLUSIVE:
            exploitability = "Inconclusive (Requires manual review)"
            sandbox_note = f"Sandbox execution was inconclusive ({validation.execution_summary})."
            summary = (
                f"Unconfirmed finding: Automated simulation was inconclusive for {title}. "
                f"Prioritization relies on scanner CVSS and threat intelligence baseline."
            )
            action = "Perform manual analyst verification on the endpoint."
            conf = 0.50
        else:
            exploitability = "Unvalidated (No sandbox run)"
            sandbox_note = "No sandbox validation has been executed for this canonical issue."
            summary = f"Finding {title} awaits sandbox validation. Scoring uses neutral validation prior."
            action = "Run sandbox validation to establish empirical exploitability."
            conf = 0.50

        return LLMContextualAnalysis(
            contextual_summary=summary,
            exploitability_assessment=exploitability,
            sandbox_evidence_synthesis=sandbox_note,
            recommended_action=action,
            confidence=conf,
            model_used=f"{settings.llm_provider}:{settings.llm_model}" if settings.llm_enabled else "mock-context-engine",
        )

    def _validate_synthesis(self, value: dict[str, Any], provider: str) -> dict[str, Any]:
        """Normalize provider output before it can influence analyst-facing context."""
        bounded = dict(value)
        bounded.setdefault("provider_used", provider)
        bounded.setdefault("model_used", settings.llm_model or "unknown")
        bounded.setdefault("evidence_basis", [])
        bounded.setdefault("uncertainty", [])
        try:
            return LLMContext.model_validate(bounded).model_dump()
        except (TypeError, ValueError):
            logger.warning("LLM provider '%s' returned an invalid synthesis schema.", provider)
            raise

    def synthesize_context(
        self,
        issue_title: str,
        cwe_primary: str,
        views_dict: dict[str, Any] | None,
        sandbox_verdict: str,
        sandbox_evidence: list[dict[str, Any]] | None,
        asset_criticality: str,
        internet_facing: bool,
        threat_cves: list[str],
    ) -> dict[str, Any]:
        """
        Synthesize finding context, empirical sandbox evidence, and business impact.
        Returns a structured dictionary with LLM analysis.
        """
        if not settings.llm_enabled:
            return self._mock_synthesis(
                issue_title, cwe_primary, sandbox_verdict, asset_criticality, "offline_disabled"
            )

        provider = (settings.llm_provider or "groq").lower()
        api_key = settings.llm_api_key.strip()

        if provider != "mock" and not api_key:
            logger.warning(f"LLM provider '{provider}' requested but no API key configured. Falling back to mock.")
            return self._mock_synthesis(
                issue_title, cwe_primary, sandbox_verdict, asset_criticality, f"mock_missing_key_{provider}"
            )

        raw_prompt = (
            f"Vulnerability Title: {issue_title}\n"
            f"Primary CWE: {cwe_primary}\n"
            f"Asset Criticality: {asset_criticality} (Internet Facing: {internet_facing})\n"
            f"Known CVEs: {threat_cves}\n"
            f"Empirical Sandbox Verdict: {sandbox_verdict}\n"
            f"Contextual Views: {json.dumps(views_dict or {})}\n"
            f"Sandbox Evidence Excerpts: {json.dumps(sandbox_evidence or [])}\n"
        )
        redacted_prompt = redact_secrets(raw_prompt) or raw_prompt

        system_instruction = (
            "You are an expert cybersecurity triage analyst. Analyze the provided vulnerability findings and empirical sandbox test evidence.\n"
            "Return ONLY a valid JSON object matching this exact schema:\n"
            "{\n"
            '  "exploitability_assessment": "Short narrative assessment of real exploitability anchored in sandbox probe evidence.",\n'
            '  "business_impact_analysis": "Short narrative of business impact based on asset criticality and exposure.",\n'
            '  "remediation_guidance": "Specific, actionable technical remediation steps.",\n'
            '  "evidence_basis": ["Specific input or artifact supporting the assessment."],\n'
            '  "uncertainty": ["What remains unverified or simulation-limited."],\n'
            '  "confidence_score": 0.85\n'
            "}"
        )

        try:
            if provider == "groq":
                return self._validate_synthesis(
                    self._call_groq(redacted_prompt, system_instruction, api_key), provider
                )
            elif provider == "openai":
                return self._validate_synthesis(
                    self._call_openai(redacted_prompt, system_instruction, api_key), provider
                )
            elif provider == "gemini":
                return self._validate_synthesis(
                    self._call_gemini(redacted_prompt, system_instruction, api_key), provider
                )
            else:
                return self._mock_synthesis(
                    issue_title, cwe_primary, sandbox_verdict, asset_criticality, "mock_provider"
                )
        except Exception as exc:
            logger.warning(f"LLM API call to provider '{provider}' failed: {exc}. Falling back to mock synthesis.")
            return self._mock_synthesis(
                issue_title, cwe_primary, sandbox_verdict, asset_criticality, f"mock_fallback_error_{provider}"
            )

    def _call_groq(self, prompt: str, system: str, api_key: str) -> dict[str, Any]:
        """Call Groq API (OpenAI-compatible chat completions)."""
        model = settings.llm_model or "llama-3.3-70b-versatile"
        url = "https://api.groq.com/openai/v1/chat/completions"
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": prompt},
            ],
            "response_format": {"type": "json_object"},
            "temperature": 0.2,
        }

        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
                "User-Agent": "AI-Assisted Triage/1.0",
            },
            method="POST",
        )

        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            content_str = data["choices"][0]["message"]["content"]
            parsed = json.loads(content_str)
            parsed["provider_used"] = "groq"
            parsed["model_used"] = model
            return parsed

    def _call_openai(self, prompt: str, system: str, api_key: str) -> dict[str, Any]:
        """Call OpenAI API (chat completions)."""
        model = settings.llm_model or "gpt-4o-mini"
        url = "https://api.openai.com/v1/chat/completions"
        payload = {
            "model": model,
            "messages": [
                {"role": "system", "content": system},
                {"role": "user", "content": prompt},
            ],
            "response_format": {"type": "json_object"},
            "temperature": 0.2,
        }

        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
                "User-Agent": "AI-Assisted Triage/1.0",
            },
            method="POST",
        )

        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            content_str = data["choices"][0]["message"]["content"]
            parsed = json.loads(content_str)
            parsed["provider_used"] = "openai"
            parsed["model_used"] = model
            return parsed

    def _call_gemini(self, prompt: str, system: str, api_key: str) -> dict[str, Any]:
        """Call Google Gemini REST API."""
        model = settings.llm_model or "gemini-1.5-flash"
        url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
        payload = {
            "contents": [{"parts": [{"text": f"{system}\n\n{prompt}"}]}],
            "generationConfig": {"responseMimeType": "application/json", "temperature": 0.2},
        }

        req = urllib.request.Request(
            url,
            data=json.dumps(payload).encode("utf-8"),
            headers={"Content-Type": "application/json"},
            method="POST",
        )

        with urllib.request.urlopen(req, timeout=15) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            content_str = data["candidates"][0]["content"]["parts"][0]["text"]
            parsed = json.loads(content_str)
            parsed["provider_used"] = "gemini"
            parsed["model_used"] = model
            return parsed

    def _mock_synthesis(
        self, issue_title: str, cwe: str, sandbox_status: str, asset_crit: str, provider_tag: str
    ) -> dict[str, Any]:
        """Deterministic offline fallback synthesis when LLM is offline or disabled."""
        if sandbox_status == "simulated_match":
            expl = f"Empirical lab validation ({sandbox_status}) confirmed probe reproducibility for {cwe} under test conditions."
            conf = 0.85
        elif sandbox_status == "simulated_no_match":
            expl = f"Empirical lab validation ({sandbox_status}) failed to reproduce {cwe} probe response; finding priority downgraded."
            conf = 0.65
        else:
            expl = f"Sandbox validation outcome ({sandbox_status}) is inconclusive; relying on multi-view scanner metrics for {cwe}."
            conf = 0.50

        return LLMContext(
            exploitability_assessment=expl,
            business_impact_analysis=f"Asset criticality '{asset_crit}' requires prioritized triage and remediation scoping.",
            remediation_guidance=f"Apply strict input validation, output encoding, or parameterized queries to mitigate {cwe}.",
            evidence_basis=[f"sandbox_verdict={sandbox_status}", f"cwe={cwe}"],
            uncertainty=["Offline simulation does not prove exploitability."],
            confidence_score=conf,
            provider_used=provider_tag,
            model_used="deterministic-rules-engine",
        ).model_dump()


llm_prioritizer_service = LLMPrioritizerService()
llm_prioritizer = llm_prioritizer_service
